### ISSUE TITLE
Would it be possible to provide the training scripts?

### ISSUE THREAD

**Issue by senisioi** [dumitrescustefan/Romanian-Transformers#5]
Thanks for this great resource! 
Would it be possible to provide the training scripts?

**Comment by dumitrescustefan** [comment]
Unfortunately, the training itself was done by Sampo in a CSC cluster (in Finland). 

If it helps, it was trained with the standard code in google's official BERT repo, nothing special there (standard params, 1M steps, etc).

We're working on an new transformer model that we're training it in-house, for that I hope we'll be able to put the training code up.

**Comment by senisioi** [comment]
It helps indeed. Thanks!
